version: '3.5'

services:
  sipit.api:
    image: ${DOCKER_REGISTRY-}sipitapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CUSTOMER_SERVICE_URL=http://sipitcustomers
      - MENU_SERVICE_URL=http://sipitmenu
    build:
      context: .
      dockerfile: SipIt.api/Dockerfile
    networks: 
      sipitnet:
        aliases:
          - sipitapi
    ports: 
      - "5005:80"

  sipit.customers:
    image: ${DOCKER_REGISTRY-}sipitcustomers
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: SipIt.customers/Dockerfile
    networks: 
      sipitnet:
        aliases:
          - sipitcustomers
    ports: 
      - "5006:80"

  sipit.menu:
    image: ${DOCKER_REGISTRY-}sipitmenu
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: SipIt.menu/Dockerfile
    networks:
      sipitnet:
        aliases:
          - sipitmenu
    ports:
      - "5007:80"

networks: 
  sipitnet:
    name: sipitnet
  
